public abstract  class AccountExtensionBase {
    @TestVisible
	public static final String SUCCESS_CODE = '0000';
    @TestVisible
    public static final String QUERY_EXCEPTION_CODE = '1001';
    @TestVisible
    public static final String CALLOUT_EXCEPTION_CODE = '1002';
    @TestVisible
    public static final String FOUND_DUP_ALLOW_CREATE = '1010';
    @TestVisible
    public static final String FOUND_DUP_NOT_ALLOW_CREATE = '1011';
    @TestVisible
    public static final String FOUND_DUP_MORE_THAN_30_NOT_ALLOW_CREATE = '0005'; 
}