@Istest
public class KnowledgeReportControllerTest {
	@istest
    static void test(){
        KnowledgeReportController.getAdvisoryKnowledge();
        KnowledgeReportController.getBranchComKnowledge();
        KnowledgeReportController.getCampaignCenterKnowledge();
        KnowledgeReportController.getProductKnowledge();
        KnowledgeReportController.getWorkInstructionKnowledge();
        
         KnowledgeReportController.getTipKnowledge();
         KnowledgeReportController.getSalesCommKnowledge();
    }
}